### PR TITLE
Fix for cmake fetchcontent

### PR DESCRIPTION
**Pull request by mikkoi**
Fix for issue https://github.com/libcheck/check/issues/238 and some cleaning.
Set policy CMP0090 to avoid unintentionally dirtying user's locale CMake Package Registry.

### CODE REVIEW

**Comment by brarcher** [comment]
I've not heard of FetchContent before. It sounds rather useful. Thanks for looking into this and enabling support for it?

Is there anything that can be done to add testing to ensure that it continues working in the future?

**Comment by mikkoi** [comment]
I created a test in Travis. It builds an example project which uses Check in two different ways. Build script in 'travis.sh`.

**Comment by unindented** [comment]
@mikkoi what's the purpose of this submodule in the diff of this PR?

Screen Shot 2020-01-13 at 1 58 58 PM

**Comment by mikkoi** [comment]
tests/cmake_project_usage_test is used to test the solution. It is only done in Travis CI. That's why it isn't actually part of CMake build, just a separate CMake project.

**Comment by mikkoi** [comment]
Marvelous! Travis is running CMake 3.12. FetchContent is supported but FetchContent_MakeAvailable() is not available until CMake 3.14. ... Time for some backwards compatibility spaghetti! :-)

**Comment by unindented** [comment]
@mikkoi haha yup, this is what I have to do in my projects:

```
include(FetchContent)
if(${CMAKE_VERSION} VERSION_LESS 3.14)
  include(cmake/FetchContent_MakeAvailable.cmake)
endif()
```

Where `cmake/FetchContent_MakeAvailable.cmake` contains something like this:

```
macro(FetchContent_MakeAvailable NAME)
  FetchContent_GetProperties(${NAME})
  if(NOT ${NAME}_POPULATED)
    FetchContent_Populate(${NAME})
    add_subdirectory(${${NAME}_SOURCE_DIR} ${${NAME}_BINARY_DIR})
  endif()
endmacro()
```

**Comment by mikkoi** [comment]
Thank you. That is a good solution. And very Cmake like, I think.

**Comment by unindented** [comment]
I've pointed my project to your branch, and it works correctly!

**Pull request merged**
