### PR TITLE
clock_gettime.c: Use __APPLE__ instead of __MACH__

### PR DESCRIPTION
**Pull request by nirbheek**
Hurd also defines `__MACH__`, but it does not have `mach_absolute_time` or `mach/clock.h`. Use the more strict `__APPLE__` instead.

### CODE REVIEW

**Comment by brarcher** [comment]
Jenkins: ok to test

^ that is necessary to start the remaining tests, please ignore.

**Comment by nirbheek** [comment]
Strange. The tests were passing, and then the PR told me it needed a merge, and after the merge they're failing again.

**Comment by brarcher** [comment]
Correct, the failures are unrelated. For some reason (that I'll trying to track down) the tests running on OSX are now encountering sporadic failures, maybe due to a more recent version of OSX than Check 0.10.0 was tested against.

I appreciate your change, thanks for submitting it. I'm running the tests again to see if they will pass. If not, I'll manually promote the changes.

**Comment by brarcher** [comment]
In addition to this fix, if you are interested would you mind submitting a change for the [AUTHORS](https://github.com/libcheck/check/blob/master/AUTHORS) file, adding an entry for yourself?

**Comment by nirbheek** [comment]
It seemed a little presumptuous to me to so that for such a trivial patch. :)

Thanks for taking care of this! We at GStreamer have been working on some fixes for libcheck while building with MSVC on Windows. Will add myself when submitting a PR for those. :)

**Comment by brarcher** [comment]
I look forward to seeing the MSVC related changes.

Recently-ish I added hooks so that the Check project would build using the CI provider [AppVeyor](https://ci.appveyor.com/project/brarcher46583/check/build/1.0.166/job/n3oa8ow6edsv5go4). Now pull requests will attempt to build and unit tests against MSVC and CLI tools from Visual Studios. If you have fixes which would not be caught by that testing, if you can also propose additional tests that would be helpful. (:

**Pull request merged**
