### PR TITLE
Convert README to README.md.

### PR DESCRIPTION
**Pull request by jd-boyd**
Also add travis and appveyor status icons.

This addresses issue #32.

### CODE REVIEW

**Comment by brarcher** [comment]
Jenkins: ok to test

**Comment by brarcher** [comment]
The make target for generating a pre-release failed with the following:
```
$ make prereleasecheck
...
08:00:25 Making all in .
08:00:25 make[4]: Entering directory `/scratch/jenkins/workspace/check-prereleasecheck-github/check-0.10.0/_build'
08:00:25 make[4]: *** No rule to make target `README.md', needed by `all-am'.  Stop.
```

**Comment by jd-boyd** [comment]
I'm a bit tempted to make a script to strip the images from the README.md file and generate a README as a target so that this doesn't have to be a `foreign` package.

**Comment by jd-boyd** [comment]
I went with generating README from README.md by stripping out the Build Status images (the rest I deemed looked as good as the original non-markdown version did when viewed as plain text).  It passed make prereleasecheck locally, so hopefully this is the final version.

**Comment by brarcher** [comment]
The autotools based builds under Travis-CI are now failing. The output from Travis-CI is not intuitive, as the unit tests pass:
```
The command "if [ $USE_CMAKE == "NO" ] ; then make check ; fi" exited with 0.
```
then the build is marked in error:
```
Done. Your build exited with 1.
```

Building this locally, I see the following fail:
```
Making check in .
fgrep -v "Build Status]" README.md > README
fgrep: README.md: No such file or directory
make[1]: *** [README] Error 2
```
It seems then that the proposed change may not allow for building out of tree, because README.md may not be in the current directory.

What if the Makefile were change to reference the location of README.md?
```
README:
        fgrep -v "Build Status]" $(top_srcdir)/README.md > $@
```
When I attempted this locally building out of tree, it did work:
```
fgrep -v "Build Status]" ../README.md > README
```

**Comment by jd-boyd** [comment]
> What if the Makefile were change to reference the location of README.md?

Thank you, I applied that change.

**Comment by brarcher** [comment]
Looks good. Thanks!

**Pull request merged**
