### PR TITLE
Drop the remaining cvsignore files

### PR DESCRIPTION
**Pull request by whot**
The main .cvsignore file got deleted in 6f5da9a032 but that commit missed the
ones in the various directories.

### CODE REVIEW

**Comment by whot** [comment]
CI failure seems to be unrelated

**Comment by mikkoi** [comment]
A bit of history here. The very first commit we have in the repository is the following:

```
commit b69fd64ac6a3da7c1f31d614424e511d009ca45a
Author: (no author) <(no author)@64e312b2-a51f-0410-8e61-82d0ca0eb02a>
Date:   Tue May 29 22:42:54 2001 +0000

    New repository initialized by cvs2svn.
    
    git-svn-id: svn+ssh://svn.code.sf.net/p/check/code/trunk@1 64e312b2-a51f-0410-8e61-82d0ca0eb02a
```

Twenty years has passed! At least we have given ourselves enough time to deprecate CVS.

**Comment by whot** [comment]
well, for those swimming in nostalgia getting the cvsignore files back is only a git revert away ;)

**Comment by brarcher** [comment]
CI failure is unrelated, should be mitigated in 
https://github.com/libcheck/check/pull/328

I'll update this PR so it picks that up

**Comment by brarcher** [comment]
Thanks for the change!

**Pull request merged**
