### PR TITLE
Added Mick Beaver to AUTHORS.

### PR DESCRIPTION
**Pull request by mickbeaver**

### CODE REVIEW

**Comment by brarcher** [comment]
Jenkins: ok to test

**Comment by brarcher** [comment]
Can you merge the latest changes from master into this branch? Otherwise, the pull will not work.

**Comment by mickbeaver** [comment]
I think I have done this now. Does it look good on your end?

-Mick

**Comment by brarcher** [comment]
Looks good. Although the change will not affect the code, I still have to wait for the build to finish before merging it.

Thanks!

**Pull request merged**
